# -*- coding: utf-8 -*-
"""TP_SQLite_Python_Pandas_Colab_A_Larhlimi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jzrOA9CofrxUlUTryOuuCd16uEydo24

La seance du 29-09

-Introduction sur les bases de donnees

-SQL

-Manipuler un notebook
"""



"""# TP — Manipuler une base SQLite avec Python et Pandas

**Auteur : A. Larhlimi**

## Objectifs
À la fin de ce notebook, vous saurez :
- créer une base SQLite et un modèle relationnel ;
- insérer, consulter, filtrer, modifier et supprimer des données ;
- relier plusieurs tables avec `JOIN` ;
- utiliser `COUNT`, `SUM`, `AVG`, `MIN`, `MAX`, `GROUP BY` et `HAVING` ;
- exécuter et afficher les requêtes SQL avec `pandas`.

> Le notebook est autonome et conçu pour être exécuté de haut en bas dans Google Colab.

## 1. SQLite, `sqlite3` et Pandas

**SQLite** est un SGBD relationnel léger : toute la base peut être stockée dans un simple fichier. Contrairement à un SGBD client-serveur (PostgreSQL, MySQL…), il n'est pas nécessaire de lancer un serveur séparé.

- Une **connexion** ouvre l'accès à la base.
- Un **curseur** permet d'envoyer des instructions SQL.
- `commit()` valide les modifications de la transaction.
- `close()` ferme proprement la connexion.
- `pandas.read_sql_query()` permet d'exécuter un `SELECT` et de récupérer directement le résultat dans un `DataFrame`.
"""

import sqlite3 #
import pandas as pd #
from pathlib import Path #

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

DB_PATH = "gestion_ventes.db"

# Pour rendre le notebook reproductible, on supprime l'ancienne base
# si elle existe déjà, puis on la recrée.
if Path(DB_PATH).exists():
    Path(DB_PATH).unlink()

# Ouverture/création de la base SQLite.
conn = sqlite3.connect(DB_PATH) #

# SQLite n'active pas les contraintes de clés étrangères par défaut
# pour chaque nouvelle connexion : on les active explicitement.
conn.execute("PRAGMA foreign_keys = ON;")

# Le curseur servira pour CREATE, INSERT, UPDATE, DELETE...
cursor = conn.cursor()

pd.DataFrame({
    "Élément": ["Base", "Connexion", "Clés étrangères"],
    "Valeur": [DB_PATH, "ouverte", "activées"]
})

"""## 2. Création du modèle relationnel

Nous utiliserons quatre tables :

- **clients** : informations sur les clients ;
- **produits** : catalogue des produits ;
- **commandes** : une commande appartient à un client ;
- **details_commandes** : lignes reliant commandes et produits.

Relations : `clients 1—N commandes`, `commandes 1—N details_commandes`, `produits 1—N details_commandes`.

Quelques contraintes importantes :
- `PRIMARY KEY` identifie chaque ligne ;
- `FOREIGN KEY` garantit les relations ;
- `NOT NULL` interdit une valeur absente ;
- `UNIQUE` interdit les doublons sur une colonne.
"""

cursor.executescript("""
CREATE TABLE clients (
    id_client INTEGER PRIMARY KEY,
    nom TEXT NOT NULL,
    ville TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    telephone TEXT
);

CREATE TABLE produits (
    id_produit INTEGER PRIMARY KEY,
    nom_produit TEXT NOT NULL,
    categorie TEXT NOT NULL,
    prix REAL NOT NULL CHECK (prix >= 0),
    stock INTEGER NOT NULL CHECK (stock >= 0)
);

CREATE TABLE commandes (
    id_commande INTEGER PRIMARY KEY,
    id_client INTEGER NOT NULL,
    date_commande TEXT NOT NULL,
    statut TEXT NOT NULL,
    FOREIGN KEY (id_client) REFERENCES clients(id_client)
);

CREATE TABLE details_commandes (
    id_detail INTEGER PRIMARY KEY,
    id_commande INTEGER NOT NULL,
    id_produit INTEGER NOT NULL,
    quantite INTEGER NOT NULL CHECK (quantite > 0),
    prix_unitaire REAL NOT NULL CHECK (prix_unitaire >= 0),
    FOREIGN KEY (id_commande) REFERENCES commandes(id_commande),
    FOREIGN KEY (id_produit) REFERENCES produits(id_produit),
    UNIQUE (id_commande, id_produit)
);
""")

conn.commit()

# Affichage de la liste des tables avec Pandas.
pd.read_sql_query(
    "SELECT name AS table_sqlite FROM sqlite_master WHERE type='table' ORDER BY name;",
    conn
)

"""**Interprétation :** les quatre tables du modèle commercial sont maintenant créées. Les clés étrangères protègent la cohérence entre clients, commandes, produits et lignes de commande.

## 3. Insertion de données

Nous allons combiner :
- `execute()` pour une insertion unique ;
- `executemany()` pour plusieurs lignes ;
- les paramètres `?`, qui séparent les données du texte SQL et évitent la concaténation dangereuse.
"""

# Exemple avec execute() : insertion d'un premier client.
cursor.execute(
    "INSERT INTO clients (id_client, nom, ville, email, telephone) VALUES (?, ?, ?, ?, ?)",
    (1, "Amal Benali", "Casablanca", "amal@example.com", "0610000001")
)

# Insertion de plusieurs clients avec executemany().
clients = [
    (2, "Wissal Mounir", "Csablanca", "wissal05moun@gmail.com", "0610000002"),
    (3, "Asmaa Mriouch", "Casablanca", "asmaamriouch6@gmail.com", None),
    (4, "Omar Tazi", "Marrakech", "omar@example.com", "0610000004"),
    (5, "Lina El Fassi", "Casablanca", "lina@example.com", None),
    (6, "Mehdi Berrada", "Tanger", "mehdi@example.com", "0610000006"),
    (7, "Nora Amrani", "Settat", "nora@example.com", "0610000007"),
    (8, "Karim Chraibi", "Fès", "karim@example.com", None)
]
cursor.executemany(
    "INSERT INTO clients (id_client, nom, ville, email, telephone) VALUES (?, ?, ?, ?, ?)",
    clients
)

produits = [
    (1, "Ordinateur portable", "Informatique", 8500.00, 12),
    (2, "Souris sans fil", "Accessoires", 180.00, 60),
    (3, "Clavier mécanique", "Accessoires", 650.00, 35),
    (4, "Écran 27 pouces", "Informatique", 2400.00, 18),
    (5, "Casque audio", "Audio", 950.00, 30),
    (6, "Webcam HD", "Accessoires", 520.00, 25),
    (7, "SSD externe 1 To", "Stockage", 1100.00, 22),
    (8, "Microphone USB", "Audio", 1250.00, 15),
    (9, "Station d'accueil", "Accessoires", 1450.00, 10),
    (10, "Tablette graphique", "Création", 3200.00, 8),
    # Produit volontairement jamais commandé : utile pour LEFT JOIN.
    (11, "Projecteur portable", "Multimédia", 4800.00, 5)
]
cursor.executemany(
    "INSERT INTO produits VALUES (?, ?, ?, ?, ?)",
    produits
)

commandes = [
    (1, 1, "2026-01-12", "Livrée"),
    (2, 2, "2026-01-18", "Livrée"),
    (3, 1, "2026-02-03", "Livrée"),
    (4, 3, "2026-02-14", "Livrée"),
    (5, 4, "2026-03-02", "Livrée"),
    (6, 5, "2026-03-19", "Livrée"),
    (7, 2, "2026-04-05", "Livrée"),
    (8, 6, "2026-04-21", "En préparation"),
    (9, 1, "2026-05-09", "Livrée"),
    (10, 7, "2026-05-17", "Livrée"),
    (11, 3, "2026-06-08", "Annulée"),
    (12, 5, "2026-06-25", "Livrée")
]
cursor.executemany(
    "INSERT INTO commandes VALUES (?, ?, ?, ?)",
    commandes
)

details = [
    (1, 1, 1, 1, 8500.00), (2, 1, 2, 2, 180.00),
    (3, 2, 4, 1, 2400.00), (4, 2, 3, 1, 650.00),
    (5, 3, 5, 2, 950.00), (6, 3, 6, 1, 520.00),
    (7, 4, 7, 1, 1100.00), (8, 4, 2, 3, 180.00),
    (9, 5, 1, 1, 8500.00), (10, 5, 8, 1, 1250.00),
    (11, 6, 10, 1, 3200.00), (12, 6, 3, 2, 650.00),
    (13, 7, 9, 1, 1450.00), (14, 7, 2, 2, 180.00),
    (15, 8, 4, 2, 2400.00), (16, 8, 6, 2, 520.00),
    (17, 9, 7, 2, 1100.00), (18, 9, 8, 1, 1250.00),
    (19, 10, 5, 1, 950.00), (20, 10, 2, 1, 180.00),
    (21, 11, 1, 1, 8500.00), (22, 11, 3, 1, 650.00),
    (23, 12, 4, 1, 2400.00), (24, 12, 9, 1, 1450.00)
]
cursor.executemany(
    "INSERT INTO details_commandes VALUES (?, ?, ?, ?, ?)",
    details
)

conn.commit()

pd.read_sql_query("""
SELECT
    (SELECT COUNT(*) FROM clients) AS nb_clients,
    (SELECT COUNT(*) FROM produits) AS nb_produits,
    (SELECT COUNT(*) FROM commandes) AS nb_commandes,
    (SELECT COUNT(*) FROM details_commandes) AS nb_lignes
""", conn)

"""**Interprétation :** le jeu de données contient plusieurs villes, catégories, dates, clients récurrents et un produit jamais commandé. Cela permettra de construire des requêtes réalistes.

## 4. Consultation avec `SELECT`

### 4.1 `SELECT *`
`*` demande toutes les colonnes de la table.
"""

pd.read_sql_query("SELECT * FROM clients;", conn)

"""### 4.2 Sélectionner seulement certaines colonnes
On peut limiter le résultat aux informations utiles.
"""

pd.read_sql_query(
    "SELECT nom_produit, categorie, prix FROM produits;",
    conn
)

"""### 4.3 `DISTINCT`
`DISTINCT` élimine les valeurs dupliquées dans le résultat.
"""

pd.read_sql_query(
    "SELECT DISTINCT categorie FROM produits ORDER BY categorie;",
    conn
)

"""### 4.4 `WHERE`, `ORDER BY` et `LIMIT`
Cherchons les trois produits les plus chers dont le prix dépasse 1 000 DH.
"""

requete = """
SELECT nom_produit, categorie, prix
FROM produits
WHERE prix > ?
ORDER BY prix ASC
LIMIT 1;
"""

pd.read_sql_query(requete, conn, params=(1000,))

"""**Interprétation :** `WHERE` filtre les lignes avant l'affichage, `ORDER BY ... DESC` classe du plus grand au plus petit et `LIMIT 3` ne conserve que trois résultats.

## 5. Filtrage des données

Les opérateurs suivants permettent de construire des conditions plus précises.
"""

# AND : produits informatiques coûtant plus de 2 000 DH.
pd.read_sql_query("""
SELECT nom_produit, categorie, prix
FROM produits
WHERE categorie = 'Informatique' AND prix > 2000
ORDER BY prix DESC;
""", conn)

# OR et NOT : clients situés à Casablanca ou Settat,
# sauf un client précis.
pd.read_sql_query("""
SELECT nom, ville
FROM clients
WHERE (ville = 'Casablanca' OR ville = 'Settat')
  AND NOT nom = 'Nora Amrani'
ORDER BY ville, nom;
""", conn)

# IN : plusieurs catégories autorisées.
pd.read_sql_query("""
SELECT nom_produit, categorie, prix
FROM produits
WHERE categorie IN ('Audio', 'Stockage', 'Création')
ORDER BY categorie, prix;
""", conn)

# BETWEEN : intervalle inclusif.
pd.read_sql_query("""
SELECT nom_produit, prix
FROM produits
WHERE prix BETWEEN 500 AND 1500
ORDER BY prix;
""", conn)

# LIKE : recherche textuelle.
pd.read_sql_query("""
SELECT nom_produit, categorie
FROM produits
WHERE nom_produit LIKE '%USB%' OR nom_produit LIKE '%sans fil%';
""", conn)

# IS NULL : clients dont le téléphone n'est pas renseigné.
pd.read_sql_query("""
SELECT nom, ville, telephone
FROM clients
WHERE telephone IS NULL;
""", conn)

"""**Interprétation :** `AND` exige plusieurs conditions simultanément, `OR` accepte l'une ou l'autre, `IN` teste une liste, `BETWEEN` un intervalle, `LIKE` un motif textuel et `IS NULL` l'absence de valeur.

## 6. Modification avec `UPDATE`

Pour bien voir l'effet de la modification, affichons d'abord le produit concerné, modifions son stock avec une requête paramétrée, puis réaffichons-le.
"""

# Avant modification
pd.read_sql_query(
    "SELECT id_produit, nom_produit, stock FROM produits WHERE id_produit = 6;",
    conn
)

# Mise à jour paramétrée.
nouveau_stock = 40
id_produit = 6

cursor.execute(
    "UPDATE produits SET stock = ? WHERE id_produit = ?",
    (nouveau_stock, id_produit)
)
conn.commit()

# Après modification
pd.read_sql_query(
    "SELECT id_produit, nom_produit, stock FROM produits WHERE id_produit = 6;",
    conn
)

"""**Interprétation :** seule la ligne dont `id_produit = 6` a été modifiée. Une clause `WHERE` oubliée dans un `UPDATE` modifierait toutes les lignes.

## 7. Suppression avec `DELETE`

Pour ne pas perturber les analyses suivantes, nous créons un client temporaire sans commande, puis nous le supprimons.
"""

# Ajout d'un client temporaire.
cursor.execute(
    "INSERT INTO clients (id_client, nom, ville, email, telephone) VALUES (?, ?, ?, ?, ?)",
    (99, "Client Temporaire", "Settat", "temporaire@example.com", None)
)
conn.commit()

pd.read_sql_query("SELECT * FROM clients WHERE id_client = 99;", conn)

# Suppression ciblée.
cursor.execute("DELETE FROM clients WHERE id_client = ?", (99,))
conn.commit()

# Le DataFrame vide confirme la suppression.
pd.read_sql_query("SELECT * FROM clients WHERE id_client = 99;", conn)

"""## 8. Jointures

Une jointure combine des lignes provenant de plusieurs tables grâce à leurs clés.

### 8.1 `INNER JOIN` — clients ayant passé des commandes
La jointure relie `clients.id_client` à `commandes.id_client`.
"""

pd.read_sql_query("""
SELECT c.nom AS client, co.id_commande, co.date_commande, co.statut
FROM clients AS c
INNER JOIN commandes AS co
    ON c.id_client = co.id_client
ORDER BY co.date_commande;
""", conn)

"""### 8.2 Produits commandés et montant des lignes

Une ligne de commande référence un produit par `id_produit`. Le montant de ligne est calculé par `quantite × prix_unitaire`.
"""

pd.read_sql_query("""
SELECT
    dc.id_commande,
    p.nom_produit,
    dc.quantite,
    dc.prix_unitaire,
    ROUND(dc.quantite * dc.prix_unitaire, 2) AS montant_ligne
FROM details_commandes AS dc
INNER JOIN produits AS p
    ON dc.id_produit = p.id_produit
ORDER BY dc.id_commande, p.nom_produit;
""", conn)

"""### 8.3 `LEFT JOIN` — conserver aussi les produits jamais commandés

Contrairement à `INNER JOIN`, `LEFT JOIN` conserve toutes les lignes de la table située à gauche.
"""

pd.read_sql_query("""
SELECT
    p.nom_produit,
    COALESCE(SUM(dc.quantite), 0) AS quantite_commandee
FROM produits AS p
LEFT JOIN details_commandes AS dc
    ON p.id_produit = dc.id_produit
LEFT JOIN commandes AS co
    ON dc.id_commande = co.id_commande
   AND co.statut <> 'Annulée'
GROUP BY p.id_produit, p.nom_produit
ORDER BY quantite_commandee DESC, p.nom_produit;
""", conn)

"""**Interprétation :** le produit jamais commandé reste visible avec une quantité égale à 0 grâce à `LEFT JOIN` et `COALESCE`.

## 9. Fonctions d'agrégation

Les fonctions d'agrégation résument plusieurs lignes :
- `COUNT()` compte ;
- `SUM()` additionne ;
- `AVG()` calcule une moyenne ;
- `MIN()` et `MAX()` donnent les extrêmes.

Dans les analyses de ventes suivantes, les commandes **annulées sont exclues du chiffre d'affaires**.
"""

pd.read_sql_query("""
SELECT
    COUNT(*) AS nombre_clients
FROM clients;
""", conn)

pd.read_sql_query("""
SELECT
    COUNT(*) AS nombre_commandes,
    COUNT(DISTINCT id_client) AS clients_ayant_commande
FROM commandes
WHERE statut <> 'Annulée';
""", conn)

pd.read_sql_query("""
SELECT
    ROUND(AVG(prix), 2) AS prix_moyen,
    MIN(prix) AS prix_minimum,
    MAX(prix) AS prix_maximum
FROM produits;
""", conn)

# Chiffre d'affaires total : somme des montants des lignes
# appartenant aux commandes non annulées.
pd.read_sql_query("""
SELECT
    ROUND(SUM(dc.quantite * dc.prix_unitaire), 2) AS chiffre_affaires_total
FROM details_commandes AS dc
JOIN commandes AS co ON co.id_commande = dc.id_commande
WHERE co.statut <> 'Annulée';
""", conn)

# Le panier moyen doit d'abord calculer le montant de chaque commande,
# puis faire la moyenne de ces montants.
pd.read_sql_query("""
WITH montants_commandes AS (
    SELECT
        co.id_commande,
        SUM(dc.quantite * dc.prix_unitaire) AS montant
    FROM commandes AS co
    JOIN details_commandes AS dc
        ON co.id_commande = dc.id_commande
    WHERE co.statut <> 'Annulée'
    GROUP BY co.id_commande
)
SELECT ROUND(AVG(montant), 2) AS panier_moyen
FROM montants_commandes;
""", conn)

"""## 10. `GROUP BY` et `HAVING`

`GROUP BY` forme des groupes de lignes afin de calculer un agrégat pour chaque groupe.

**Différence fondamentale :**
- `WHERE` filtre les **lignes avant** le regroupement ;
- `HAVING` filtre les **groupes après** `GROUP BY`.

### 10.1 Chiffre d'affaires par client
"""

pd.read_sql_query("""
SELECT
    c.id_client,
    c.nom,
    ROUND(SUM(dc.quantite * dc.prix_unitaire), 2) AS chiffre_affaires
FROM clients AS c
JOIN commandes AS co ON c.id_client = co.id_client
JOIN details_commandes AS dc ON co.id_commande = dc.id_commande
WHERE co.statut <> 'Annulée'
GROUP BY c.id_client, c.nom
ORDER BY chiffre_affaires DESC;
""", conn)

"""### 10.2 Chiffre d'affaires et quantité vendue par produit"""

pd.read_sql_query("""
SELECT
    p.nom_produit,
    COALESCE(SUM(CASE WHEN co.statut <> 'Annulée' THEN dc.quantite ELSE 0 END), 0) AS quantite_vendue,
    ROUND(COALESCE(SUM(CASE WHEN co.statut <> 'Annulée'
                            THEN dc.quantite * dc.prix_unitaire ELSE 0 END), 0), 2) AS chiffre_affaires
FROM produits AS p
LEFT JOIN details_commandes AS dc ON p.id_produit = dc.id_produit
LEFT JOIN commandes AS co ON dc.id_commande = co.id_commande
GROUP BY p.id_produit, p.nom_produit
ORDER BY chiffre_affaires DESC;
""", conn)

"""### 10.3 Chiffre d'affaires par catégorie"""

pd.read_sql_query("""
SELECT
    p.categorie,
    ROUND(SUM(dc.quantite * dc.prix_unitaire), 2) AS chiffre_affaires
FROM produits AS p
JOIN details_commandes AS dc ON p.id_produit = dc.id_produit
JOIN commandes AS co ON dc.id_commande = co.id_commande
WHERE co.statut <> 'Annulée'
GROUP BY p.categorie
ORDER BY chiffre_affaires DESC;
""", conn)

"""### 10.4 Nombre de commandes par client"""

pd.read_sql_query("""
SELECT
    c.nom,
    COUNT(co.id_commande) AS nombre_commandes
FROM clients AS c
LEFT JOIN commandes AS co
    ON c.id_client = co.id_client
   AND co.statut <> 'Annulée'
GROUP BY c.id_client, c.nom
ORDER BY nombre_commandes DESC, c.nom;
""", conn)

"""### 10.5 Panier moyen par client"""

pd.read_sql_query("""
WITH montant_par_commande AS (
    SELECT
        co.id_commande,
        co.id_client,
        SUM(dc.quantite * dc.prix_unitaire) AS montant
    FROM commandes AS co
    JOIN details_commandes AS dc ON co.id_commande = dc.id_commande
    WHERE co.statut <> 'Annulée'
    GROUP BY co.id_commande, co.id_client
)
SELECT
    c.nom,
    ROUND(AVG(mpc.montant), 2) AS panier_moyen
FROM clients AS c
JOIN montant_par_commande AS mpc ON c.id_client = mpc.id_client
GROUP BY c.id_client, c.nom
ORDER BY panier_moyen DESC;
""", conn)

"""### 10.6 `HAVING` — clients dont le CA dépasse 5 000 DH"""

pd.read_sql_query("""
SELECT
    c.nom,
    ROUND(SUM(dc.quantite * dc.prix_unitaire), 2) AS chiffre_affaires
FROM clients AS c
JOIN commandes AS co ON c.id_client = co.id_client
JOIN details_commandes AS dc ON co.id_commande = dc.id_commande
WHERE co.statut <> 'Annulée'
GROUP BY c.id_client, c.nom
HAVING SUM(dc.quantite * dc.prix_unitaire) > 5000
ORDER BY chiffre_affaires DESC;
""", conn)

"""**Interprétation :** `WHERE` a d'abord exclu les commandes annulées ; `HAVING` a ensuite conservé uniquement les groupes de clients dont le chiffre d'affaires calculé dépasse 5 000 DH.

## 11. Requête finale de synthèse

Construisons un tableau de pilotage client combinant :
- plusieurs `JOIN` ;
- un filtre `WHERE` ;
- `COUNT`, `SUM` et calculs ;
- `GROUP BY` ;
- `HAVING` ;
- `ORDER BY`.

Le **panier moyen** est calculé comme `CA / nombre de commandes distinctes`.
"""

requete_synthese = """
SELECT
    c.nom AS client,
    COUNT(DISTINCT co.id_commande) AS nombre_commandes,
    SUM(dc.quantite) AS quantite_totale_achetee,
    ROUND(SUM(dc.quantite * dc.prix_unitaire), 2) AS chiffre_affaires,
    ROUND(
        SUM(dc.quantite * dc.prix_unitaire)
        / COUNT(DISTINCT co.id_commande),
        2
    ) AS panier_moyen
FROM clients AS c
JOIN commandes AS co
    ON c.id_client = co.id_client
JOIN details_commandes AS dc
    ON co.id_commande = dc.id_commande
WHERE co.statut <> 'Annulée'
GROUP BY c.id_client, c.nom
HAVING SUM(dc.quantite * dc.prix_unitaire) >= 1000
ORDER BY chiffre_affaires DESC, nombre_commandes DESC;
"""

pd.read_sql_query(requete_synthese, conn)

"""**Interprétation :** ce tableau synthétise l'activité commerciale par client. Il illustre comment SQL peut transformer des données transactionnelles réparties sur plusieurs tables en indicateurs métier directement exploitables.

## 12. Bonnes pratiques

### Requêtes paramétrées
Préférer :
`cursor.execute("... WHERE id = ?", (valeur,))`

à la concaténation de chaînes. Les paramètres réduisent notamment le risque d'**injection SQL** et gèrent correctement l'échappement des valeurs.

### Transactions
Plusieurs modifications liées peuvent être regroupées dans une transaction. `commit()` valide ; `rollback()` annule en cas d'erreur.

### Intégrité
Les clés primaires identifient les lignes. Les clés étrangères empêchent la création de relations incohérentes lorsqu'elles sont activées dans SQLite.

### Fermeture
Une connexion doit être fermée lorsqu'elle n'est plus nécessaire. Nous le ferons à la toute fin, après les exercices et leurs corrigés.
"""

# Exemple pédagogique de transaction avec rollback :
# la modification est volontairement annulée.
stock_avant = pd.read_sql_query(
    "SELECT stock FROM produits WHERE id_produit = 2;", conn
).iloc[0, 0]

try:
    cursor.execute("UPDATE produits SET stock = stock - ? WHERE id_produit = ?", (2, 2))
    # Ici, d'autres opérations pourraient suivre.
    conn.rollback()  # Démonstration : on annule volontairement.
except Exception:
    conn.rollback()
    raise

stock_apres = pd.read_sql_query(
    "SELECT stock FROM produits WHERE id_produit = 2;", conn
).iloc[0, 0]

pd.DataFrame({
    "Moment": ["Avant la transaction", "Après rollback"],
    "Stock": [stock_avant, stock_apres]
})

"""## 13. Exercices

Essayez de résoudre les exercices suivants **avant d'ouvrir la section Corrigé**.

1. Afficher les trois produits les plus chers.
2. Calculer le nombre de produits par catégorie.
3. Trouver le client ayant effectué le plus de commandes non annulées.
4. Calculer le chiffre d'affaires par mois.
5. Trouver les produits jamais commandés.
6. Trouver les clients dont le chiffre d'affaires est supérieur au chiffre d'affaires moyen par client.
7. Calculer, pour chaque ville, le nombre de clients et le chiffre d'affaires réalisé.
8. Afficher les catégories dont le chiffre d'affaires dépasse 3 000 DH.

# Corrigé des exercices

### Exercice 1 — Trois produits les plus chers
"""

pd.read_sql_query("""
SELECT nom_produit, prix
FROM produits
ORDER BY prix DESC
LIMIT 3;
""", conn)

"""### Exercice 2 — Nombre de produits par catégorie"""

pd.read_sql_query("""
SELECT categorie, COUNT(*) AS nombre_produits
FROM produits
GROUP BY categorie
ORDER BY nombre_produits DESC, categorie;
""", conn)

"""### Exercice 3 — Client ayant effectué le plus de commandes"""

pd.read_sql_query("""
SELECT c.nom, COUNT(co.id_commande) AS nombre_commandes
FROM clients AS c
JOIN commandes AS co ON c.id_client = co.id_client
WHERE co.statut <> 'Annulée'
GROUP BY c.id_client, c.nom
ORDER BY nombre_commandes DESC, c.nom
LIMIT 1;
""", conn)

"""### Exercice 4 — Chiffre d'affaires par mois"""

pd.read_sql_query("""
SELECT
    strftime('%Y-%m', co.date_commande) AS mois,
    ROUND(SUM(dc.quantite * dc.prix_unitaire), 2) AS chiffre_affaires
FROM commandes AS co
JOIN details_commandes AS dc ON co.id_commande = dc.id_commande
WHERE co.statut <> 'Annulée'
GROUP BY strftime('%Y-%m', co.date_commande)
ORDER BY mois;
""", conn)

"""### Exercice 5 — Produits jamais commandés"""

pd.read_sql_query("""
SELECT p.id_produit, p.nom_produit
FROM produits AS p
LEFT JOIN details_commandes AS dc ON p.id_produit = dc.id_produit
WHERE dc.id_detail IS NULL;
""", conn)

"""### Exercice 6 — Clients au-dessus du CA moyen par client"""

pd.read_sql_query("""
WITH ca_clients AS (
    SELECT
        c.id_client,
        c.nom,
        SUM(dc.quantite * dc.prix_unitaire) AS ca
    FROM clients AS c
    JOIN commandes AS co ON c.id_client = co.id_client
    JOIN details_commandes AS dc ON co.id_commande = dc.id_commande
    WHERE co.statut <> 'Annulée'
    GROUP BY c.id_client, c.nom
)
SELECT nom, ROUND(ca, 2) AS chiffre_affaires
FROM ca_clients
WHERE ca > (SELECT AVG(ca) FROM ca_clients)
ORDER BY ca DESC;
""", conn)

"""### Exercice 7 — Clients et chiffre d'affaires par ville"""

pd.read_sql_query("""
SELECT
    c.ville,
    COUNT(DISTINCT c.id_client) AS nombre_clients,
    ROUND(COALESCE(SUM(
        CASE WHEN co.statut <> 'Annulée'
             THEN dc.quantite * dc.prix_unitaire
             ELSE 0 END
    ), 0), 2) AS chiffre_affaires
FROM clients AS c
LEFT JOIN commandes AS co ON c.id_client = co.id_client
LEFT JOIN details_commandes AS dc ON co.id_commande = dc.id_commande
GROUP BY c.ville
ORDER BY chiffre_affaires DESC;
""", conn)

"""### Exercice 8 — Catégories dont le CA dépasse 3 000 DH"""

pd.read_sql_query("""
SELECT
    p.categorie,
    ROUND(SUM(dc.quantite * dc.prix_unitaire), 2) AS chiffre_affaires
FROM produits AS p
JOIN details_commandes AS dc ON p.id_produit = dc.id_produit
JOIN commandes AS co ON dc.id_commande = co.id_commande
WHERE co.statut <> 'Annulée'
GROUP BY p.categorie
HAVING SUM(dc.quantite * dc.prix_unitaire) > 3000
ORDER BY chiffre_affaires DESC;
""", conn)

"""## 14. Conclusion

Vous avez parcouru une chaîne complète :

**création → insertion → SELECT → filtrage → UPDATE/DELETE → JOIN → agrégations → GROUP BY/HAVING → analyse métier**

SQLite est particulièrement adapté à l'apprentissage, au prototypage et aux applications locales. Les mêmes concepts SQL constituent ensuite une base solide pour travailler avec PostgreSQL, MySQL ou d'autres SGBD relationnels.
"""

# Fermeture propre de la connexion.
conn.close()

pd.DataFrame({
    "Ressource": ["Connexion SQLite"],
    "État final": ["fermée proprement"]
})